name: Winfirm
url: https://winfirm.top/
baseurl: /blog
description: None

permalink: /:title.html

highlighter: pygments
paginate: 20

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins: ['jekyll-paginate']
